### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by JeffGowan** [StarlingXWeb/starlingx-website#22]
Hi - looking through the StarlingX site I noticed a few broken links but I'm not sure where the links should go.

  
Page: https://www.starlingx.io/

The Freenode #starlingx goes here: https://freenode.net/ (nothing about StarlingX) it seems a bit confusing.

  
Page: https://www.starlingx.io/software/
  
All the individual configuration management, fault management, etc links are broken.
  
  
Page: https://www.starlingx.io/community/
  
Contribute: Developer guide link is broken

**Comment by jimmytipit** [comment]
Hi - Thank you for the report! All links are now fixed and changes are in production.
